name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  release:
    name: test
    timeout-minutes: 2
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        # No simple reciept to curl it, so, let's just wait for it to be up
        options: >-
          --health-cmd "sleep 5"
          --health-interval 3s
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
      - name: Get tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: vars
        run: echo "name=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Create release
        if: steps.vars.outputs.tag != null
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          draft: false
