name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Azurite
        run: npm install -g azurite
      - name: Start Azurite
        shell: bash
        run: azurite-blob &
      - name: Wait for Azurite starts
        run: sleep 5 && curl http://localhost:10000/
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
